version: '3'
services:
  redis:
    image: redis:4.0.1

  daemon:
    build:
      context: ./server
      dockerfile: Dockerfile.daemon
    volumes:
      - db:/data
    environment:
      - TICK_RATE=60
      - PERSIST_ALL=1
    healthcheck:
      test: ["CMD-SHELL", "[ -f /data/db.sqlite3 ] && exit 0 || exit 1"]
      interval: 60s
      timeout: 1s
      retries: 3

  cacher:
    build:
      context: ./server
      dockerfile: Dockerfile.cacher
    volumes:
      - db:/data:ro
    environment:
      - TICK_RATE=60
      - PERSIST_ALL=1
    depends_on:
      - redis
      - daemon

  api:
    build:
      context: ./server
      dockerfile: Dockerfile.api
    environment:
      - PERSIST_ALL=1
    ports:
      - '8080:8080/tcp'
    depends_on:
      - redis
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1/health"]
      interval: 60s
      timeout: 5s
      retries: 3

volumes:
  db:
